### ISSUE TITLE
查询文件上传状态接口地址错误

### ISSUE THREAD

**Issue by q127981** [AttackingCat/easy-esign#1]
正确接口地址为：https://{host}/v3/files/{fileId}
代码里少了一个s

![image](https://github.com/user-attachments/assets/210814ed-e15c-44e1-858d-1cf084fbfd4b)
![image](https://github.com/user-attachments/assets/947e342c-d110-4cae-ad7d-1db0919a4eef)

**Comment by AttackingCat** [comment]
已修复，请使用implementation 'io.github.attackingcat:easy-esign-starter:1.0.8'

**Comment by AttackingCat** [comment]
抱歉，由于个人时间有限并未对所有接口进行验证，仅对文件合同主要流程进行了测试。
此地址已修复，请使用 implementation 'io.github.attackingcat:easy-esign-starter:1.0.9'，如果您有额外的时间，可以对未覆盖到的接口进行pr，工作日当日可以进行版本推送（maven central，阿里云次日）！
